### ISSUE TITLE
Tracking issue for repl tasks

### ISSUE THREAD

**Issue by luketpeterson** [trueagi-io/hyperon-experimental#398]
- [x] repl build project
- [x] basic MeTTa runner
- [x] load modules (pure MeTTa)
- [ ] integration with Python modules
    - [ ] Make Python integration an optional build dependency (cargo feature)
    - [ ] Rust loader for Python MeTTa modules
    - [ ] Make hyperonc and hyperonpy available to repl environment
    - [ ] Wrapper to manage python dispatch for python modules called from Rust eval
- [ ] cmd-line args (e.g. to run MeTTa files non-interactively)
- [ ] Bootstrapping / cfg management (Module directories / paths, Python version to use, Persistent space?)
- [ ] custom syntax highlighting
- [ ] custom tab completion (currently only path args are supported)
